### ISSUE TITLE
Path Sum

### ISSUE THREAD

**Issue by ghost** [logeable/logeable.github.io#1]
破坏树 不行吧

**Comment by logeable** [comment]
修改sum就好了把～
bool hasPathSum(TreeNode *root,int sum)
{
if(root==nullptr)
{
return false;
}
if(root->left==nullptr&&root->right==nullptr)
{
return sum==root->val;
}
if(root->left)
{
if(hasPathSum(root->left,sum-root->val))
{
return true;
}
}
if(root->right)
{
if(hasPathSum(root->right,sum-root->val))
{
return true;
}
}
return false;
}

2014-12-08 14:26 GMT+08:00 David.Liu notifications@github.com:

**Comment by logeable** [comment]
看来得学一下怎么加入评论功能...各种错误自己都没发现

2014-12-08 14:41 GMT+08:00 logeable lee logeable@gmail.com:

**Comment by ghost** [comment]
还有溢出呢

**Comment by logeable** [comment]
这样应该可以吧，本来提交一直错误，后来才发现原来是
if(total==tmp->val)
{
         return true;
}
直接被我写成return total==tmp->val;
。。。。
跟踪的累死了。
bool hasPathSum(TreeNode _root,int sum)
{
if(root==nullptr)
{
return false;
}
stack<TreeNode_> st;
stack<int> si;
st.push(root);
si.push(sum);
while(!st.empty())
{
auto tmp=st.top();
auto total=si.top();
if(tmp->left==nullptr&&tmp->right==nullptr)
{
if(total==tmp->val)
{
    return true;
}
}
st.pop();
si.pop();
if(tmp->right)
{
    si.push(total-tmp->val);
st.push(tmp->right);
}
if(tmp->left)
{
    si.push(total-tmp->val);
st.push(tmp->left);
}
}
return false;
}

2014-12-08 15:03 GMT+08:00 David.Liu notifications@github.com:

**Comment by ghost** [comment]
呃 这个溢出的可能性还是低的。
但是 设定的都是int, 有负数的话，会溢出的吧。

**Comment by logeable** [comment]
什么是有负数的话会溢出啊。
例如给出这样的输入

```
[1,-2,-3,1,3,-2,#,-1](层序遍历)，2
```

代码运行正常啊。
如果说是担心total-tmp->val会溢出的话，那么应该写大数类还是抛出异常啊？

2014-12-08 15:43 GMT+08:00 David.Liu notifications@github.com:

**Comment by ghost** [comment]
sum=2
root=20 后面的都是正的，只有一个分支是存在负的,并且最终的sum会到2
你传入的都是sum - x - y...
那么其他分支的累加起来起来可能负爆了.
同理也可能正爆了。

**Comment by logeable** [comment]
那用层次遍历应该可以吧

2014-12-08 22:14 GMT+08:00 David.Liu notifications@github.com:

**Comment by logeable** [comment]
恩，是我想错了，这样改了过后，还有问题不？请指教

#include <iostream>
#include <limits>
#include <stack>
using namespace std;

struct TreeNode
{
TreeNode _left;
TreeNode *right;
int val;
TreeNode(int x=0):val(x),left(nullptr),right(nullptr)
{
}
};
bool hasPathSum(TreeNode *root,int sum)
{
if(root==nullptr)
{
return false;
}
stack<TreeNode_> st;
stack<int> si;
st.push(root);
si.push(sum);
while(!st.empty())
{
auto tmp=st.top();
auto total=si.top();
if(tmp->left==nullptr&&tmp->right==nullptr)
{
if(total==tmp->val)
{
    return true;
}
}
st.pop();
si.pop();
if(tmp->right)
{
    if(total&0x80000000!=(total-tmp->val)&0x80000000)
    {
        continue;
    }
    si.push(total-tmp->val);
st.push(tmp->right);
}
if(tmp->left)
{
    if(total&0x80000000!=(total-tmp->val)&0x80000000)
    {
        continue;
    }
    si.push(total-tmp->val);
st.push(tmp->left);
}
}
return false;
}

int main(int argc,char *argv[])
{
int max=numeric_limits<int>::max();
int min=numeric_limits<int>::min();
auto tree=new TreeNode(20);
tree->left=new TreeNode(-2);
tree->right=new TreeNode(-18);
tree->left->left=new TreeNode(min);
tree->left->right=new TreeNode(max);

cout<<boolalpha<<hasPathSum(tree,2)<<endl;//输出true

}

**Comment by logeable** [comment]
哎，还是有问题，我真的不会了，请赐教。

2014-12-08 23:11 GMT+08:00 logeable lee logeable@gmail.com:

> 恩，是我想错了，这样改了过后，还有问题不？请指教
> 
> #include <iostream>
> #include <limits>
> #include <stack>
> using namespace std;
> 
> struct TreeNode
> {
> TreeNode _left;
> TreeNode *right;
> int val;
> TreeNode(int x=0):val(x),left(nullptr),right(nullptr)
> {
> }
> };
> bool hasPathSum(TreeNode *root,int sum)
> {
> if(root==nullptr)
> {
> return false;
> }
> stack<TreeNode_> st;
> stack<int> si;
> st.push(root);
> si.push(sum);
> while(!st.empty())
> {
> auto tmp=st.top();
> auto total=si.top();
> if(tmp->left==nullptr&&tmp->right==nullptr)
> {
> if(total==tmp->val)
> {
>     return true;
> }
> }
> st.pop();
> si.pop();
> if(tmp->right)
> {
>     if(total&0x80000000!=(total-tmp->val)&0x80000000)
>     {
>         continue;
>     }
>     si.push(total-tmp->val);
> st.push(tmp->right);
> }
> if(tmp->left)
> {
>     if(total&0x80000000!=(total-tmp->val)&0x80000000)
>     {
>         continue;
>     }
>     si.push(total-tmp->val);
> st.push(tmp->left);
> }
> }
> return false;
> }
> 
> int main(int argc,char *argv[])
> {
> int max=numeric_limits<int>::max();
> int min=numeric_limits<int>::min();
> auto tree=new TreeNode(20);
> tree->left=new TreeNode(-2);
> tree->right=new TreeNode(-18);
> tree->left->left=new TreeNode(min);
> tree->left->right=new TreeNode(max);
> 
> cout<<boolalpha<<hasPathSum(tree,2)<<endl;//输出true
> 
> }

**Comment by logeable** [comment]
难道要把一条路径上的所有值放入一个容器，然后让最大和最小相加，直到加完，在判断是不是等于sum。。。

2014-12-08 23:18 GMT+08:00 logeable lee logeable@gmail.com:

> 哎，还是有问题，我真的不会了，请赐教。
> 
> 2014-12-08 23:11 GMT+08:00 logeable lee logeable@gmail.com:
> 
> > 恩，是我想错了，这样改了过后，还有问题不？请指教
> > 
> > #include <iostream>
> > #include <limits>
> > #include <stack>
> > using namespace std;
> > 
> > struct TreeNode
> > {
> > TreeNode _left;
> > TreeNode *right;
> > int val;
> > TreeNode(int x=0):val(x),left(nullptr),right(nullptr)
> > {
> > }
> > };
> > bool hasPathSum(TreeNode *root,int sum)
> > {
> > if(root==nullptr)
> > {
> > return false;
> > }
> > stack<TreeNode_> st;
> > stack<int> si;
> > st.push(root);
> > si.push(sum);
> > while(!st.empty())
> > {
> > auto tmp=st.top();
> > auto total=si.top();
> > if(tmp->left==nullptr&&tmp->right==nullptr)
> > {
> > if(total==tmp->val)
> > {
> >     return true;
> > }
> > }
> > st.pop();
> > si.pop();
> > if(tmp->right)
> > {
> >     if(total&0x80000000!=(total-tmp->val)&0x80000000)
> >     {
> >         continue;
> >     }
> >     si.push(total-tmp->val);
> > st.push(tmp->right);
> > }
> > if(tmp->left)
> > {
> >     if(total&0x80000000!=(total-tmp->val)&0x80000000)
> >     {
> >         continue;
> >     }
> >     si.push(total-tmp->val);
> > st.push(tmp->left);
> > }
> > }
> > return false;
> > }
> > 
> > int main(int argc,char *argv[])
> > {
> > int max=numeric_limits<int>::max();
> > int min=numeric_limits<int>::min();
> > auto tree=new TreeNode(20);
> > tree->left=new TreeNode(-2);
> > tree->right=new TreeNode(-18);
> > tree->left->left=new TreeNode(min);
> > tree->left->right=new TreeNode(max);
> > 
> > cout<<boolalpha<<hasPathSum(tree,2)<<endl;//输出true
> > 
> > }
